services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/auth/prisma/schema.prisma && pnpm prisma generate --schema apps/auth/prisma/schema.prisma && pnpm run start:dev auth"
    depends_on:
      - postgres
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  weather:
    build:
      context: .
      dockerfile: ./apps/weather/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/weather/prisma/schema.prisma && pnpm prisma generate --schema apps/weather/prisma/schema.prisma && pnpm run start:dev weather"
    depends_on:
      - postgres
    env_file:
      - ./apps/weather/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
