apiVersion: v2
name: weather-backend
description: A Helm chart for AppNation Weather Backend
type: application
version: 0.1.0
appVersion: '1.16.0'
dependencies:
  - name: rabbitmq
    version: 15.2.1
    repository: https://charts.bitnami.com/bitnami
