apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - image: '<WEATHER_REGISTRY>/weather/production:latest'
          imagePullPolicy: Always
          name: weather
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: connectionString
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: connectionString
