apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather
  name: weather
spec:
  ports:
    - name: 'http'
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: weather
  type: NodePort
